name: doctor-plus
on: [push]
jobs:
  build_job:
    runs-on: ubuntu-latest
    needs: checkstyle_job
    name: buildme
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run int test
        run: ./gradlew integrationTest
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'