name: doctor-plus
on: [push]
jobs:
  build_and_push_to_docker_job:
    runs-on: ubuntu-latest
    needs: checkstyle_job
    name: buildme
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run int test
        run: ./gradlew integrationTest
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: kulikuliboy
          password: kulikuliboy
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kulikuliboy/doctorPlus:${{ github.ref }}

  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'